#!/usr/bin/env bash
#a Bash script that gives you information about the school 
count=1
while [ "$count" -lt 101 ]
do
	if [ $((count%15)) = 0 ]
        then
		echo "FizzBuzz"
     	elif [ $((count%3)) = 0 ]
	then
		echo "Fizz"
       	elif [ $((count%5)) = 0 ]
       	then
	       	echo "Buzz"
     	else	
	      	echo "$count"
	fi
((count++))
done
