#!/usr/bin/env bash                                                                                                                                      
#A Bash script that displays Best School 10 times
while [ $counter -lt 10]
do 
echo "Best School"
done 
