#!/usr/bin/env bash                                                                                                                                      
#A Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
COUNTER=1
while [ $COUNTER -le 10 ]
do 
	echo "Best School"
	if [ $COUNTER == 9 ]
	then
		echo "Hi"
	fi
	((COUNTER++))
done
