#!/usr/bin/env bash
#Bash script that gives you information about the School file
file="School"
if [ -e "$file" ]
then
    echo "holbertonschool file exists"
    if [ -s "$file" ]
    then
        echo "holbertonschool file is not empty"
    else
        echo "School file is empty"
    fi
    if [ -f "$file" ]
    then
        echo "School is a regular file"
    fi
else
    echo "School file does not exist"
fi
