#!/usr/bin/env bash
#Write a Bash script that:creates the file /var/run/myscript.pid containing its PID, displays To infinity and beyond indefinitely, displays I hate the kill command when receiving a SIGTERM signal, displays Y U no love me?! when receiving a SIGINT signal, deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ >> /var/run/myscript.pid;

trap '
echo  "I hate the kill command"
rm -rf /var/run/myscript.pid
exit' 15

trap '
echo "Y U no love me?!" ' 2
trap 'rm -rf /var/run/myscrip.pid' 3

while true 
do
	echo "TO infinity and beyond"
	sleep 2
done
