#!/usr/bin/env bash
#Write a Bash script that:creates the file /var/run/myscript.pid containing its PID, displays To infinity and beyond indefinitely, displays I hate the kill command when receiving a SIGTERM signal, displays Y U no love me?! when receiving a SIGINT signal, deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

sudo touch /var/run/holbertonscript.pid

sudo bash -c 'echo $$ > /var/run/holbertonscript.pid'

while true

do

	    echo "To infinity and beyond"

	    sleep 2

	    trap 'echo "I hate the kill command"; sudo rm /var/run/holbertonscript.pid; exit' SIGTERM

	    trap 'echo "Y U no love me?!"' SIGINT

	    trap 'sudo rm /var/run/holbertonscript.pid; exit' SIGQUIT
done
